#!/usr/bin/env node

// compiles directory of widgets/ to a single JS file

const fs = require('fs');
const path = require('path');

let widgetsBase = "./widgets/";

let widgetsData = {};

let items = fs.readdirSync(widgetsBase);
for (let item of items) {
    let itemPath = path.join(widgetsBase, item);

    // check if item is file
    let stats = fs.statSync(itemPath);

    if (stats.isDirectory())
        continue

    let filename = item.slice(0, item.lastIndexOf("."));

    let isSettings = filename.endsWith(".settings");
    if (isSettings) {
        filename = filename.slice(0, filename.lastIndexOf("."));
    }

    if (!widgetsData[filename])
        widgetsData[filename] = {}

    let contents = fs.readFileSync(itemPath, "utf-8");

    let key;
    if (isSettings) {
        key = "settings";
    } else if (item.endsWith("js")) {
        key = "script"
    } else {
        key = "html"
    }
    widgetsData[filename][key] = contents;
}

let baseFileContents = "// Autogenerated file!\n\nlet widgets = ";

let totalFileContents = baseFileContents + JSON.stringify(widgetsData);

fs.writeFileSync(path.join("./gen/", "widgetsBuild.js"), totalFileContents);